version: '3'
services:
  php:
    build: .
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
  composer:
    image: composer
    command: "composer install"
    volumes:
      - ./app:/app